### ISSUE TITLE
Should not continue to execute spark job if uploadJar is failed in the function `submitJob`

### ISSUE THREAD

**Issue by aaronlin** [KKBOX/spark-deployer#4]

**Comment by pishen** [comment]
這個也一樣，因為 uploadJar() 會噴 exception 所以其實不會繼續執行，我再想想有沒有更好的寫法。

**Comment by pishen** [comment]
Actually, it won't, instead it throws an exception (as a side effect) and stop. Would be good if there's an elegant functional way to write this.

**Comment by pishen** [comment]
This one should be fixed now.
